jobs:
  dependencies:
    working_directory: ~/workspace/workspace
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ../workspace/workspace
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          command: cd  ../workspace/workspace && npm install
      - store_artifacts:
          path: /node_modules      
  test:
    working_directory: ~/workspace/workspace
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - run:
          command: cd  ../workspace/workspace && ls
    
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - dependencies
      - test