jobs:
  test:
    working_directory: ~/workspace/workspace
    docker:
      - image: circleci/node:6-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ../workspace/workspace
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          command: cd  ../workspace/workspace && npm install karma && npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test