jobs:
  test:
    working_directory: ~/workspace/workspace
    docker:
      - image: circleci/node:6-browsers
        environment:
           CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          command: cd  ../workspace/workspace && npm install && npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test