version: 2.1
workflows:
  test_my_app:
    jobs:
      - dependencies
      - test
   
jobs:
  dependencies:
    docker:
      - image: weboaks/node-karma-protractor-chrome
    steps:
      - checkout
      - run: cd ./workspace && npm i 

jobs:
  test:
    docker:
      - image: weboaks/node-karma-protractor-chrome
    steps:
      - checkout
      - run: cd ./workspace && npm i && npm test
