version: 2.1
jobs:
  test:
    docker:
      - image: 'ubuntu'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/workspace     
    steps:
      - run: ls
     
workflows:
  version: 2
  build_and_test:
    jobs:
      - test