jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - node/install-npm
      - node/install-packages:
          app-dir: ~/workspace 
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          command: npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test