jobs:
  test:
    working_directory: ~/workspace/workspace   
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - node/install-npm
      - run:
          command: npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test