
jobs:
  dependencies:
    working_directory: ~/workspace/workspace
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ../workspace/workspace
          cache-path: node_modules
          override-ci-command: npm install
   
  test:
    working_directory: ~/workspace/workspace
    executor:
      name: node/default
    steps:
      run: 
        - ls    
orbs:
  node: circleci/node@4.1.0

workflows:
  version: 2
  test_my_app:
    jobs:
      - dependencies
      - test