version: 2.1
jobs:
  test:
    docker:
      - image: 'cimg/node:14.14.0'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: node --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - test