version: 2.1
workflows:
  test_my_app:
    jobs:
      - dependencies
   
jobs:
  dependencies:
    docker:
      - image: weboaks/node-karma-protractor-chrome
    steps:
      - checkout
      - run: ls   
