version: 2.1
jobs:
  test:
    docker:
      - image: 'ubuntu'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: 
        command: cd ./workspace && ng test
        name: Run Tests
workflows:
  version: 2
  build_and_test:
    jobs:
      - test